# 1. Promises

Given this new version of `printString`:

```js
function printString (string) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log(string)
      resolve()
    }, Math.floor(Math.random() * 100) + 1)
  })
}
```

Use `.then()` promise chain to call A, B, C in order

# 2. Async/Await

Now we are going to make our promise-based functions use `async` instead of like:

```js
const printABC = async () => {
  // await ...
}
```

Convert your function which called `printString` to use `async` and `await` rather than promises.

You shouldn't have to edit `printString` to do this.

# 3. Again, but this time with state

Now let's introduce two new functions that do the same thing:

```js
// Callback style
function addString (previous, current, callback) {
  setTimeout(() => {
    callback(null, previous + ' ' + current)
  }, Math.floor(Math.random() * 100) + 1)
}

// Promise style
function addString (previous, current) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(previous + ' ' + current)
    }, Math.floor(Math.random() * 100) + 1)
  })
}
```

Call each one to get the result of " A B C" using the three styles:

- Callback
- Promise
- Async/Await

# 4. Exceptions

Let's update the two `addString` functions to occasionally throw an error:

```js
// Callback style
function addStringCb (previous, current, callback) {
  setTimeout(() => {
    if (Math.random() > 0.8) {
      callback(new Error('cb bang!'))
    } else {
      callback(null, previous + ' ' + current)
    }
  }, Math.floor(Math.random() * 100) + 1)
}

// Promise style
function addStringPromise (previous, current) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() > 0.8) {
        reject(new Error('bang!'))
      }
      resolve(previous + ' ' + current)
    }, Math.floor(Math.random() * 100) + 1)
  })
}
```

Notice how the callback convention is to pass two items to the function, the first is if there is an error, the second (and any other additional items) are the returned values.

Make sure each of your functions is updated to handle these exceptions:

- Callback
- Promise
- Async/Await
